config/routes.rb
IpHome::Application.routes.draw do

  match '/museum' => redirect("http://momi.invisibleplayground.com")

  match '/navigation/' => 'navigation#show'
	match '/map/update' => 'map#update'
	match '/map/get_position' => 'map#get_position'

  scope "admin" do
		get "/", :controller => :admin, :action => :index
    get "/logout", :controller => :admin, :action => :logout, :as => 'logout'
		resources :pages
		resources :images
		resources :projects
		resources :tags
		resources :events
		resources :media_items
    resources :map_positions
  end

  scope ":locale", :locale => /en|de/, :as => :public do
  	match '/projects/gallery' => 'projects#gallery', :as => 'projects_gallery'
  	match '/projects/list' => 'projects#list', :as => 'projects_list'
  	match '/events/list' => 'events#list', :as => 'events_list'
  	match '/events/upcoming' => 'events#upcoming'
  	match '/media_items/list' => 'media_items#list', :as => 'media_items_list'
  	resources :projects, :only => [:show, :update]
		resources :tags, :only => [:show, :update]
		resources :events, :only => [:show, :update]
		resources :pages, :only => [:show, :update], :path => ''
	end
  
  root :to => 'navigation#index'
  

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	translates :description, :location, :title
  belongs_to :project
  attr_accessible :date, :end_date, :description_de, :description_en, :location_de, :location_en, :time, :title_de, :title_en, :url, :project_id, :direct_to_project, :direct_to_url, :disable_link
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all :order=>'date DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

	def list
		@events = Event.all :order=>'date DESC'
		@events_by_year = @events.group_by { |e| e.date.year }
    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
    end
	end	

	def upcoming
		@events = Event.all :order=>'date ASC', :limit=>3
    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
    end
	end	

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @use_end_date = false
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

		unless params[:use_end_date] == "1"
			params[:event].delete_if{ |key, value| key.match(/^end_date/) }
			params[:event][:end_date] = nil;
		end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

		unless params[:use_end_date] == "1"
			params[:event].delete_if{ |key, value| key.match(/^end_date/) }
			params[:event][:end_date] = nil;
		end

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    Use end date? <%= 
    	if @event.end_date 
	    	check_box_tag "use_end_date", "1", true
	    else 
		    check_box_tag "use_end_date"
		  end %>
  </div>
  <div class="field">
    <%= f.label :location_en %><br />
    <%= f.text_field :location_en %>
  </div>
  <div class="field">
    <%= f.label :location_de %><br />
    <%= f.text_field :location_de %>
  </div>
  <div class="field">
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </div>
  <div class="field">
    <%= f.label :title_de %><br />
    <%= f.text_field :title_de %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </div>
  <div class="field">
    <%= f.label :description_de %><br />
    <%= f.text_area :description_de %>
  </div>
  <div class="field">
    <%= f.label :url, "External URL" %>  <%= f.text_field :url %> 
    <%= f.label :direct_to_url %> <%= f.check_box :direct_to_url %>
  </div>
  <div class="field">
  	<%= f.label :project_id, "Project" %>
		<%= f.select :project_id, Project.order("title_en").collect {|p| [ p.title, p.id ] }, { :include_blank => "None" } %>
    <%= f.label :direct_to_project %> <%= f.check_box :direct_to_project %>
  </div>
  <div class="field">
      <%= f.label :disable_link %> <%= f.check_box :disable_link %>
  </div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_link.html.erb
      <% if event.disable_link %>
        <%= text %>
      <% elsif event.direct_to_url && event.url %>
        <%= link_to text, event.url, :target => "_blank" %>    
      <% elsif event.direct_to_project && event.project_id %>
        <%= link_to text, public_project_url(event.project), :class=>"nav_ajax" %>    
      <% else %>
        <%= link_to text, public_event_url(event), :class=>"nav_ajax" %>
      <% end %>

app/views/events/_upcoming.html.erb
<ul class="event_list">
<% events.each do |event| %>
	<li>
		<%= l event.date, :format=>:short %><%= l event.end_date, :format=>:short_end if event.end_date %>
		<%= event.location %><br/>    
    <%= render 'events/link', :event => event, :text => event.title %>
	</li>
<% end %>
    <!--li class="all_events"><%= link_to t("events_list"), public_events_list_url, :class=>"nav_ajax" %></li-->
</ul>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= link_to 'New Event', new_event_path %>
<h1>Listing events</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= l event.date, :format=>:long %></td>
    <td><%= event.location %></td>
    <td><%= event.title %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/events/list.html.erb
<h1><%= t('events_headline') %></h1>

<% @events_by_year.each do |year, events| %>
	<h2><%= year %></h2>
	<ul>
	<% events.each do |event| %>
		<li>
			<%= l event.date, :format=>:month_day %><% if event.end_date %> - <%= l event.end_date, :format=>:month_day%><% end %>,
			<%= event.location %>,
      <%= render 'events/link', :event => event, :text => event.title %>

		</li>
	<% end %>
	</ul>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <%= @event.location %>,
	<%= l @event.date, :format=>:long %>
	<% if @event.end_date %> 
		- <%= l @event.end_date, :format=>:long%>
	<% else %>
		<%= l @event.time, :format=>:hours_minutes %>
	<% end %>
</p>

<h1><%= @event.title %></h1>

<div>
  <%= formatize @event.description %>
</div>

<p>
<% if @event.direct_to_project && @event.project_id %>
    <%= link_to t('more_info'), public_project_url(event.project), :class=>"nav_ajax" %>    
<% else %>
    <%= link_to t('more_info'), @event.url, :target => "_blank"  if @event.url? %>    
<% end %>
</p>

<p>
<%= link_to 'Edit', edit_event_path(@event) if session[:admin] %>
<% if request.path.include?('admin') %>
  | <%= link_to 'Show public', public_event_path(@event) if session[:admin] %>
<% end %>

</p>

app/views/events/upcoming.html.erb
<%= render :partial=>'upcoming', :locals=>{:events=>@events} %>