config/routes.rb
IpHome::Application.routes.draw do

  match '/museum' => redirect("http://momi.invisibleplayground.com")

  match '/navigation/' => 'navigation#show'
	match '/map/update' => 'map#update'
	match '/map/get_position' => 'map#get_position'

  scope "admin" do
		get "/", :controller => :admin, :action => :index
    get "/logout", :controller => :admin, :action => :logout, :as => 'logout'
		resources :pages
		resources :images
		resources :projects
		resources :tags
		resources :events
		resources :media_items
    resources :map_positions
  end

  scope ":locale", :locale => /en|de/, :as => :public do
  	match '/projects/gallery' => 'projects#gallery', :as => 'projects_gallery'
  	match '/projects/list' => 'projects#list', :as => 'projects_list'
  	match '/events/list' => 'events#list', :as => 'events_list'
  	match '/events/upcoming' => 'events#upcoming'
  	match '/media_items/list' => 'media_items#list', :as => 'media_items_list'
  	resources :projects, :only => [:show, :update]
		resources :tags, :only => [:show, :update]
		resources :events, :only => [:show, :update]
		resources :pages, :only => [:show, :update], :path => ''
	end
  
  root :to => 'navigation#index'
  

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title_en, use: :slugged
  translates :title, :description_short, :description_long 
  attr_accessible :client, :description_long_de, :description_long_en, :description_short_de, :description_short_en, :in_gallery, :location, :year, :start_date, :end_date, :title_de, :title_en, :website, :image_id, :direct_to_url, :main_media_embed, :ongoing
  belongs_to :image
  has_and_belongs_to_many :tags
  has_many :media_items

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where('in_gallery >= 0').order('in_gallery ASC, title_en ASC').all
    other_projects = Project.where(:in_gallery => nil).order('title_en ASC').all
    @projects = @projects.to_a
    @projects += other_projects.to_a

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
      format.json { render json: @project }
    end
  end

	def gallery
		@projects = Project.where("in_gallery > 0").order("in_gallery ASC")
    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
    end
	end	

	def list
		@projects = Project.all
		@projects_by_year_unsorted = @projects.group_by do |p| 
			if p.start_date
				p.start_date.strftime("%Y") 
			else
				p.year
			end
		end
		@projects_by_year = @projects_by_year_unsorted.sort_by { | year, project | year }.reverse!

    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
    end
	end	
		
  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

		unless params[:use_end_date] == "1"
			params[:project].delete_if{ |key, value| key.match(/^end_date/) }
			params[:project][:end_date] = nil;
		end

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

		unless params[:use_end_date] == "1"
			params[:project].delete_if{ |key, value| key.match(/^end_date/) }
			params[:project][:end_date] = nil;
		end

		@project.tags = [] # empty tags
		if params[:project][:tag_ids]
			params[:project][:tag_ids].each do |tag_id| 
				tag = Tag.find(tag_id)
				@project.tags << tag if tag	# add new tags
			end
			params[:project].delete(:tag_ids) # do not use in update_attributes below
		end

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </div>
  <div class="field">
    <%= f.label :title_de %><br />
    <%= f.text_field :title_de %>
  </div>
  <div class="field">
    <%= f.label :description_short_en %><br />
    <%= f.text_area :description_short_en %>
  </div>
  <div class="field">
    <%= f.label :description_short_de %><br />
    <%= f.text_area :description_short_de %>
  </div>
  <div class="field">
    <%= f.label :description_long_en %><br />
    <%= f.text_area :description_long_en %>
  </div>
  <div class="field">
    <%= f.label :description_long_de %><br />
    <%= f.text_area :description_long_de %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
    <%= f.label :ongoing %>
    <%= f.check_box :ongoing %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
    Use end date? <%= 
    	if @project.end_date 
	    	check_box_tag "use_end_date", "1", true
	    else 
		    check_box_tag "use_end_date"
		  end %>
  </div>
  <div class="field">
    <%= f.label :client, "Project partner" %><br />
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %><br>
    <%= f.label :direct_to_url %> <%= f.check_box :direct_to_url %>
  </div>
  <div class="field">
  	<%= f.label :image, "Main image" %>
		<%= f.select :image_id, Image.order("title, image_file_name").collect {|i| [ i.filename_and_title, i.id ] }, { :include_blank => "None" } %>
	</div>
  <div class="field">
  	<%= f.label :main_media_embed, "or embed media instead of image" %><br>
    <%= f.text_area :main_media_embed %><br>
	</div>
  <div class="field">
    <%= f.label :in_gallery %><br />
    <%= f.number_field :in_gallery %>
  </div>

  <div class="field">	
  <%= f.label :tags %>
  <ul>
  <% Tag.all.each do |tag| %>
  	<li>
  		<%= tag.name %>
  		<input type="checkbox" id="tag_<%= tag.id %>" name="project[tag_ids][]" value="<%= tag.id %>"
  		<% if @project.tags.exists?(tag) %>
  			checked="checked"
  		<% end %>
  		/>
  	</li>
  <% end %>
  </ul>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_gallery_intro.de.html.erb
<p>Hier ist eine Auwahl unserer Arbeit. Um alle Projekte zu sehen, <%= link_to "clicke hier", public_projects_list_url, :class=>"content_ajax" %>.</p>

app/views/projects/_gallery_intro.en.html.erb
<p>Here is a selection of some of our projects. To browse all projects, <%= link_to "click here", public_projects_list_url, :class=>"content_ajax" %>.</p>

app/views/projects/_gallery_show_single.html.erb
<tr>
<td>
		<% if project.image %>
			<%= image_tag project.image.image.url(:thumb) %>
		<% end %>
</td>
<td>
    <% if project.direct_to_url %>
      <a href="<%= project.website %>" target="_blank"><%= project.title %></a>
    <% else %>
        <a href="<%= public_project_url(project) %>" class="nav_ajax"><%= project.title %></a>
    <% end %><br/> 
		<%= project.description_short %><br/>
		<!-- Keywords: <%= render 'projects/taglist', :tags => project.tags %> -->
</td>

app/views/projects/_taglist.html.erb
<% tags.each_with_index do |tag, index| %>
	<%= link_to tag.name, public_tag_url(tag), :class=>'content_ajax' %><% if index < tags.size - 1 %>,&nbsp;<% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/gallery.html.erb
<h1><%= t('project_gallery_headline') %></h1>
<%= render 'projects/gallery_intro' %>

<table>
<% @projects.each do |project| %>
	<%= render 'projects/gallery_show_single', :project=>project %>
<% end %>
</table>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path %>
<h1>Listing projects</h1>

<table>
  <tr>
  	<th>Image</th>
    <th>Title</th>
    <th>In gallery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
		<td><%= image_tag project.image.image.url(:thumb) if project.image %></td>
    <td><%= project.title %></td>
    <td><%= project.in_gallery %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/projects/list.html.erb
<h1><%= t('projects_headline') %></h1>

<% @projects_by_year.each do |year, projects| %>
	<h2><%= year %></h2>
	<table>
	<% projects.each do |project| %>
		<%= render 'projects/gallery_show_single', :project=>project %>
	<% end %>
	</table>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% if @project.main_media_embed? %>
  <%= @project.main_media_embed.html_safe %>
<% elsif @project.image %>
	<%= image_tag @project.image.image.url(:medium) %>
<% end %>

<h1><%= @project.title %></h1>

<p><%= @project.description_short %></p>

<ul>
  <!--li>Keywords: <%= render :partial=>'projects/taglist', :locals=>{:tags => @project.tags} %></li-->
  	<% if @project.start_date %>
    <li><%= t('project_date') %>: 
      <% if @project.ongoing %>
      	 <%= t('ongoing_since') + " " +	(l @project.start_date, :format=>:long) %>
      <% else %>
        <%=	l @project.start_date, :format=>:long %>
        <% if @project.end_date %> - <%= l @project.end_date, :format=>:long %> <% end %>
      <% end %>
    </li>  
  	<% else %>
  	<% end %>
    <% if @project.location? %>
      <li><%= t('project_location') %>: <%= @project.location %></li>
    <% end %>
  <% if @project.client? %>
		<li><%= t('project_partner') %>: <%= @project.client %></li>
	<% end %>
    <% if @project.website? %>
      <li>Website: <%= link_to @project.website, @project.website, :target => "_blank" %></li>	
    <% end %>
</ul>

<p><%= formatize @project.description_long %></p>

<!--
<% if @project.media_items.size > 0 %>
	<h3><%= t('media_items_headline') %></h3>
	<ul>
		<% @project.media_items.each do |media_item| %>
		<li>
		<%= render :partial=>'media_items/show_single', :locals=>{:media_item=>media_item} %>
		</li>
		<% end %>
	</ul>
<% end %>
-->

<p>
<%= link_to 'Edit', edit_project_path(@project) if session[:admin] %>
<% if request.path.include?('admin') %>
  | <%= link_to 'Show public', public_project_path(@project) if session[:admin] %>
<% end %>
</p>