config/routes.rb
IpHome::Application.routes.draw do

  match '/museum' => redirect("http://momi.invisibleplayground.com")

  match '/navigation/' => 'navigation#show'
	match '/map/update' => 'map#update'
	match '/map/get_position' => 'map#get_position'

  scope "admin" do
		get "/", :controller => :admin, :action => :index
    get "/logout", :controller => :admin, :action => :logout, :as => 'logout'
		resources :pages
		resources :images
		resources :projects
		resources :tags
		resources :events
		resources :media_items
    resources :map_positions
  end

  scope ":locale", :locale => /en|de/, :as => :public do
  	match '/projects/gallery' => 'projects#gallery', :as => 'projects_gallery'
  	match '/projects/list' => 'projects#list', :as => 'projects_list'
  	match '/events/list' => 'events#list', :as => 'events_list'
  	match '/events/upcoming' => 'events#upcoming'
  	match '/media_items/list' => 'media_items#list', :as => 'media_items_list'
  	resources :projects, :only => [:show, :update]
		resources :tags, :only => [:show, :update]
		resources :events, :only => [:show, :update]
		resources :pages, :only => [:show, :update], :path => ''
	end
  
  root :to => 'navigation#index'
  

  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name_en, use: :slugged
  translates :name, :description
  attr_accessible :name_de, :name_en, :description_de, :description_en
  has_and_belongs_to_many :projects  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order('name_en ASC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html { render :layout => ! request.xhr? }
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<div class="field">
    <%= f.label :name_en %><br />
    <%= f.text_field :name_en %>
  </div>
	
  <div class="field">
    <%= f.label :name_de %><br />
    <%= f.text_field :name_de %>
  </div>
	
  <div class="field">
    <%= f.label :description_de %><br />
    <%= f.text_area :description_de %>
  </div>
	
	<div class="field">
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<%= link_to 'New Tag', new_tag_path %>
<h1>Listing tags</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
	  <td><%= tag.name_en %> / <%= tag.name_de %></td>
    <td><%= link_to 'Show', public_tag_url(tag) %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<h1><%= @tag.name %> <%= t('projects_with_keyword') %></h1>

<%= formatize @tag.description if @tag.description %>

<table>
<% @tag.projects.each do |project| %>
	<%= render 'projects/gallery_show_single', :project=>project %>
<% end %>
</table>