config/routes.rb
IpHome::Application.routes.draw do

  match '/museum' => redirect("http://momi.invisibleplayground.com")

  match '/navigation/' => 'navigation#show'
	match '/map/update' => 'map#update'
	match '/map/get_position' => 'map#get_position'

  scope "admin" do
		get "/", :controller => :admin, :action => :index
    get "/logout", :controller => :admin, :action => :logout, :as => 'logout'
		resources :pages
		resources :images
		resources :projects
		resources :tags
		resources :events
		resources :media_items
    resources :map_positions
  end

  scope ":locale", :locale => /en|de/, :as => :public do
  	match '/projects/gallery' => 'projects#gallery', :as => 'projects_gallery'
  	match '/projects/list' => 'projects#list', :as => 'projects_list'
  	match '/events/list' => 'events#list', :as => 'events_list'
  	match '/events/upcoming' => 'events#upcoming'
  	match '/media_items/list' => 'media_items#list', :as => 'media_items_list'
  	resources :projects, :only => [:show, :update]
		resources :tags, :only => [:show, :update]
		resources :events, :only => [:show, :update]
		resources :pages, :only => [:show, :update], :path => ''
	end
  
  root :to => 'navigation#index'
  

  

end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController

	def index 
    @page = Page.where(:welcome_page => true).order('id ASC').first
    if @page
      redirect_to :controller => "pages", :action => "show", :id => @page.slug
    else
      redirect_to :controller => "pages", :action => "show", :id => 'welcome'
    end
	end

  def show
  	set_locale
		respond_to do |format|
			format.html { render :partial => "navigation/user_menu" }
  	end
  end

end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/navigation/_admin_menu.html.erb
<nav>
<h1><span>Admin</span></h1>

<ul>
	<li><%= link_to "Main Pages", pages_url %></li>
	<li><%= link_to "Subpages", pages_url(:subpages =>1) %></li>
</ul>
<ul>
	<li><%= link_to "Images", images_url %></li>
	<li><%= link_to "Projects", projects_url %></li>
	<li><%= link_to "Tags", tags_url %></li>
	<li><%= link_to "Events", events_url %></li>
	<li><%= link_to "Media Items", media_items_url %></li>
	<li><%= link_to "Map Positions", map_positions_url %></li>
</ul>
<ul>  
	<li><%= link_to "Public area", root_url %></li>
	<li><%= link_to "Logout", logout_url %></li>
</ul>
</nav>

app/views/navigation/_language_selector.html.erb
<select id="language_selector">
	<% I18n.available_locales.each do |l| %>
		<option value="<%= l %>"
			<% if l == I18n.locale %>
				selected="selected"
			<% end %>			
		>
		<%= t(l) %>
		</option>
	<% end %>
</select>

app/views/navigation/_map_explanation.de.html.erb
<p>Wenn Sie die <%= link_to 'Karte im Hintergrund', public_page_url('map'), :class=>'nav_ajax' %> bewegen, bewegt sie sich für alle.</p>

app/views/navigation/_map_explanation.en.html.erb
<p>If you move the <%= link_to 'map in the background', public_page_url('map'), :class=>'nav_ajax' %>, it will move for everyone.</p>

app/views/navigation/_user_menu.html.erb
<div class="menu_section">
	<div class="menu_label"><%= t("choose_language") %></div>
	<%= render 'navigation/language_selector' %>
</div>

<% events = Event.all( :conditions => ["date > ?", Date.yesterday],
											 :order=>'date ASC', :limit=>4) %>

<% if events.length > 0 %>
  <span class="menu_large"><%= t("events_upcoming") %></a></span><br>
  <%= render 'events/upcoming', :events => events %>
<% end %>

<span class="menu_large"><%= t("project_gallery") %></span><br>
<ul class="event_list">
    <% projects = Project.where("in_gallery > 0").order("in_gallery ASC")
       projects.each do |project| %>
    <li>
    <% if project.direct_to_url %>
      <a href="<%= project.website %>" target="_blank"><%= project.title %></a>
    <% else %>
        <a href="<%= public_project_url(project) %>" class="nav_ajax"><%= project.title %></a>
    <% end %>
    </li>        
    <% end %>
</ul>

<ul id="main_menu">
	<%#= link_to t("project_gallery"), public_projects_gallery_url, :class=>"nav_ajax" %>
  <!--li><%#= link_to t("media_items_list"), public_media_items_list_url, :class=>"nav_ajax"	%></li-->
        
	<% pages = Page.where("in_menu > 0").order("in_menu ASC")
		 pages.each do |page| %>	
		<li><a href="<%= public_page_url(page) %>" class="nav_ajax"><%= page.title %></a></li>
	<% end %>
</ul>

<div class="menu_section">
	<div>

	<a href="http://facebook.com/invisibleplayground" target="_blank"><%= image_tag('icons/fb.png', :size=>"32x32"); %></a>
	<a href="http://twitter.com/invplayground" target="_blank"><%= image_tag('icons/twitter.png', :size=>"32x32"); %></a>
	<a href="http://invisibleplayground.tumblr.com" target="_blank"><%= image_tag('icons/tumblr.png', :size=>"32x32"); %></a>
	<a href="http://flickr.com/invisibleplayground/sets" target="_blank"><%= image_tag('icons/flickr.png', :size=>"32x32"); %></a>
	<a href="https://www.youtube.com/user/BerlinIP/videos" target="_blank"><%= image_tag('icons/youtube.png', :size=>"32x32"); %></a>


<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="http://invisibleplayground.us2.list-manage1.com/subscribe/post?u=cf00edf370d9247c83fb66ed5&amp;id=54ce07e486" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
<div class="mc-field-group">
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_cf00edf370d9247c83fb66ed5_54ce07e486" value=""></div>
	<div class="clear"><input type="submit" value="<%= t('newsletter_subscribe') %>" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>

<!--End mc_embed_signup-->




	</div>
</div>

<%= render 'navigation/map_explanation' %>